alias rm='trash'
alias l2cupc='ssh l2cup@192.168.88.125 -p1408'
alias l2cupr='ssh l2cup@89.216.21.73 -p1408'
alias suroot='sudo -E -s'
alias py3='python3'
alias cl="clear"
alias cat="bat"
alias mac_server='/Applications/IDA\ Pro\ 7.0/ida.app/Contents/MacOS/dbgsrv/mac_server'
alias mac_server64='/Applications/IDA\ Pro\ 7.0/ida.app/Contents/MacOS/dbgsrv/mac_server64'
alias ldm='ld macosx_version_min 10.14 -lSystem'
alias fresh='go run $GOPATH/src/github.com/pilu/fresh/main.go'
#alias platformio='/Users/uros/.platformio/penv/bin/platformio'
alias tagsc='ctags -R --c++-kinds=+p --fields=+iaS --extras'
alias grep='rg'
alias xcodegui='sudo xcode-select -s /Applications/Development/Xcode.app/Contents/Developer'
alias xcodecli='sudo xcode-select --switch /Library/Developer/CommandLineTools'
alias btm="btm -C /Users/uros/.config/bottom/custom.toml"
alias vim="nvim"
alias ls="exa"
alias lsa="exa -laa --git --icons"
alias ll="ls -l --git --icons"
alias l="lsa"
alias tree="ls -T --icons"
alias enimal="gpg --edit-card;ssh root@10.24.0.11"
alias larch="gpg --edit-card;ssh root@10.24.111.2"
