export LC_ALL=en_US.UTF-8
export EDITOR=vim
export ZSH="$HOME/.config/.oh-my-zsh"
export ZDOTDIR="$HOME/.config/zsh"
export HISTFILE="$HOME/.config/zsh/.zsh_history"
export RIPGREP_CONFIG_PATH="$HOME/.config/ripgrep/.ripgreprc"
export _Z_DATA="$HOME/.config/.z"
export GOPATH="$HOME/Documents/Programming/go"
export PATH=$PATH:$(go env GOPATH)/bin
export PATH=$PATH:/Applications/Arduino.app/Contents/MacOS/Arduino
export PATH=$PATH:~/.platformio/penv/bin
export PATH=$PATH:~/.scripts/bin
export PATH=$PATH:/usr/local/opt/coreutils/bin
export PATH=$PATH:/usr/local/opt/rabbitmq/sbin
export PATH="/usr/local/sbin:$PATH"
#export CPATH=`xcrun --show-sdk-path`/usr/include
export PYENV_ROOT="$HOME/.applications/.pyenv"
export GNUPGHOME="$HOME/.applications/.gnupg"
export GRADLE_USER_HOME="$HOME/.applications/.gradle"
export IDAUSR="$HOME/.applications/.idapro"
export NUGET_PACKAGES="$HOME/.applications/.nuget/packages"
export NODE_REPL_HISTORY=""
export LESSHISTFILE=-
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
#gpgconf --launch gpg-agent
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export MCFLY_KEY_SCHEME=vim
export MCFLY_FUZZY=true
export PATH="/usr/local/opt/ruby/bin:/usr/local/lib/ruby/gems/3.0.1/bin:$PATH"
