export EDITOR=vim
export ZSH="$HOME/.config/.oh-my-zsh"
export ZDOTDIR="$HOME/.config/zsh"
export _Z_DATA="$HOME/.config/.z"
export GOPATH="$HOME/Documents/Programming/go"
export PATH=$PATH:$(go env GOPATH)/bin
export PATH=$PATH:/Applications/Arduino.app/Contents/MacOS/Arduino
export PATH=$PATH:~/.platformio/penv/bin
#export CPATH=`xcrun --show-sdk-path`/usr/include
export PYENV_ROOT="$HOME/.applications/.pyenv"
export GNUPGHOME="$HOME/.applocations/.gnupg"
export GRADLE_USER_HOME="$HOME/.applications/.gradle"
export IDAUSR="$HOME/.applications/.idapro"
export NUGET_PACKAGES="$HOME/.applications/.nuget/packages"
